[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "buaiir_spectra"
version = "0.1.0"
description = "Spectrometry and spectral analysis tools from BUAIIR datasets"
authors = [
    {name = "Wilfred Kisitu"},
    {name="Nalwanga Rosemary"},
    {name="Bateesa Saul Tobius"}
]
dependencies = [
    "numpy",
    "pandas",
    "openpyxl"
]

[tool.setuptools.packages.find]
where = ["src"]